const template = `Hi {{first_name}} {{last_name}},

I hope this message finds you well. You may find it surprising to know that this email was generated by an application that was built through a conversation with ChatGPT, an AI language model.

In fact, ChatGPT was able to assist Nic in the development of this app by providing valuable insights on JavaScript and React programming, as well as recommendations for popular libraries and tools.

Thanks to ChatGPT's help, we were able to quickly and easily create a powerful application that can generate and send customized emails to a list of recipients with ease. I'm excited to see where this technology will take us in the future!

Best regards,

Nic and ChatGPT`;

export default template;